#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

counter=0
while [ $counter -le 12 ]
do
	echo "Hour: $counter"
	i=1
	while [ $i -le 59 ]
	do
		echo $i
		(( i= i + 1 ))
	done
	(( counter = counter + 1 ))
done
