#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

counter=0
while [ $counter -le 12 ]
do
	echo "Hour: $counter"
	for (( i=1; i <= 59; i++ ))
	do
		echo $i
	done
	(( counter = counter + 1 ))
done
